name: Creating issue workflow

on:
    issues: 
      types: [opened]

jobs:
  greet:
    env:
        MY_ENV: "Rotimi"
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - run: ls -l
      - uses: actions/checkout@v5
      - run: ls -l
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
  label-issues:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Add urgent label
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            LABEL: "triage"
        run: gh issue edit "$ISSUE_NUMBER" --add-label "$LABEL"
      
  
    
