name: Creating issue workflow

on:
    issues: 
      types: [opened]

jobs:
  greet:
    env:
        MY_ENV: "Rotimi"
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - run: ls -l
      - uses: actions/checkout@v5
      - run: ls -l
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
          
  add-label:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          labels: |
            minor release
            bug
      - name: Add bug label
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            LABEL: "minor release"
        run: gh issue edit "$ISSUE_NUMBER" --add-label "$LABEL"
      
  
    
